---
# Variables listed here are applicable to all host groups
ansible_user: ansible
ntpserver: 192.168.1.2
interface_types: 
  - imm
  - ens0
  - ib
subnets:
  - name: management
    subnet: 172.22.0.0/16
  - name: private_1g
    subnet: 172.21.0.0/16
  - name: private_ib
    subnet: 172.20.0.0/16
interface_to_subnet:
  ens0: private_1g
  ib: private_ib
  imm: management