---
# Variables listed here are applicable to all host groups
ansible_user: ansible
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ntpserver: 192.168.1.2
interface_types: 
  - imm
  - ens0
  - ib
subnets:
  - name: management
    subnet: 172.22.0.0/16
  - name: private_1g
    subnet: 172.21.0.0/16
  - name: private_ib
    subnet: 172.20.0.0/16
interface_to_subnet:
  ens0: private_1g
  ib: private_ib
  imm: management
implementation:
  docker:
    slurm_conf_loc: ./bootstrap/etc/slurm
    implemented_group: ['freeipa', 'frontend', 'slurmctld', 'slurmdbd', 'compute', 'memory', 'dgx', 'dbs', 'gpfs']
    mountpoint: 
    config_by_group:
      freeipa:
        image: freeipa/freeipa-server:latest
        environment:
          - IPA_SERVER_IP=0.0.0.0
          - PASSWORD=Secret123
        volumes:
          - ./bootstrap/freeipa:/data:Z
      frontend: 
        image: sinonkt/docker-slurmfe:latest
      slurmctld:
        image: sinonkt/docker-slurmctld:latest
      slurmdbd:
        image: sinonkt/docker-slurmdbd:latest
      compute:
        image: sinonkt/docker-slurmd:latest
      memory:
        image: sinonkt/docker-slurmd:latest
      dgx:
        image: sinonkt/docker-slurmd:latest
      dbs:
        image: mariadb:latest
        environment:
          - MYSQL_ROOT_PASSWORD=slurm
          - MYSQL_ROOT_HOST=mysql-1
          - MYSQL_DATABASE=slurm
          - MYSQL_USER=slurm
          - MYSQL_PASSWORD=slurm
        volumes:
          - ./bootstrap/mysql:/var/lib/mysql 
      gpfs:
        image: itsthenetwork/nfs-server-alpine:latest
        environment:
         - SHARED_DIRECTORY=/gpfs
        volumes:
          - ./bootstrap/gpfs:/gpfs
  ansible:
