---
# Variables listed here are applicable to all host groups
ansible_user: ansible
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ntpserver: 192.168.1.2
interface_types: 
  - imm
  - ens0
  - ib
subnets:
  - name: management
    subnet: 172.22.0.0/16
  - name: private_1g
    subnet: 172.21.0.0/16
  - name: private_ib
    subnet: 172.20.0.0/16
interface_to_subnet:
  ens0: private_1g
  ib: private_ib
  imm: management
implementation:
  docker:
    slurm_conf_loc: ./etc/slurm
    implemented_group: ['freeipa', 'frontend', 'slurmctld', 'slurmdbd', 'compute', 'memory', 'dgx', 'dbs', 'gpfs']
    mountpoint: 
    config_by_group:
      dbs:
        image: mariadb:latest
        environment:
          - MYSQL_ROOT_PASSWORD=slurm
          - MYSQL_ROOT_HOST=mysql-1
          - MYSQL_DATABASE=slurm
          - MYSQL_USER=slurm
          - MYSQL_PASSWORD=slurm
        volumes:
          - ./srv/mysql:/var/lib/mysql 
      freeipa:
        image: freeipa/freeipa-server:latest
        environment:
          - IPA_SERVER_IP=0.0.0.0
          - PASSWORD=Secret123
        volumes:
          - ./srv/freeipa:/data:Z
      frontend: 
        image: slurmfe:latest
      slurmctld:
        image: slurmctld:latest
        depends_ons:
          - mysql-1
          - slurmdbd-1
      slurmdbd:
        image: slurmdbd:latest
        depends_ons:
          - mysql-1
      compute:
        image: slurmd:latest
      memory:
        image: slurmd:latest
      dgx:
        image: slurmd:latest
      gpfs:
        image: itsthenetwork/nfs-server-alpine:latest
        environment:
         - SHARED_DIRECTORY=/gpfs
        volumes:
          - ./srv/gpfs:/gpfs
  ansible:
