---
# This playbook contains common plays that will be run on all nodes.

- name: ensure all slurm plugins package dependecies are installed
  yum: 
    name:
    - munge-devel
    - pam-devel
    - hwloc-devel
    - lua-devel
    - mysql-devel
    - pmix-devel
    state: present
  check_mode: yes

- name: ensure all MUNGE package dependencies are installed
  yum:
    name:
    - bzip2-devel
    - openssl-devel
    - zlib-devel
    state: present
  check_mode: yes

- name: ensure all Lmod package dependencies are installed 
  yum:
    name:
    - lua-posix
    - lua
    - lua-filesystem
    - lua-devel
    - tcl
    state: present
  check_mode: yes

- name: ensure that munge service are started
  systemd:
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - munge
  check_mode: yes